# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.time_input = QtWidgets.QTimeEdit(self.centralwidget)
        self.time_input.setGeometry(QtCore.QRect(30, 80, 118, 22))
        self.time_input.setObjectName("time_input")
        self.date_input = QtWidgets.QDateEdit(self.centralwidget)
        self.date_input.setGeometry(QtCore.QRect(20, 20, 110, 22))
        self.date_input.setDateTime(QtCore.QDateTime(QtCore.QDate(2000, 1, 1), QtCore.QTime(0, 0, 0)))
        self.date_input.setObjectName("date_input")
        self.filename_input = QtWidgets.QLineEdit(self.centralwidget)
        self.filename_input.setGeometry(QtCore.QRect(180, 30, 351, 71))
        self.filename_input.setObjectName("filename_input")
        self.submit_input = QtWidgets.QPushButton(self.centralwidget)
        self.submit_input.setGeometry(QtCore.QRect(590, 60, 75, 23))
        self.submit_input.setObjectName("submit_input")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Program Launcher Schedule"))
        self.submit_input.setText(_translate("MainWindow", "add"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
